---
abstract: "Lingua::ENG::Numbers converts arbitrary numbers into human-oriented English text. Limited support is included for parsing standardly formatted numbers (i.e. 3,213.23). But no attempt has been made to handle any complex formats. Support for multiple variants of English are supported. Currently only \"American\" formatting is supported."
author:
  - 'Stephen Pandich <pandich@yahoo.com>'
build_requires:
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-ENG-Numbers
requires:
  Carp: 0
  Exporter: 0
  base: 0
  strict: 0
  vars: 0
  warnings: 0
version: 0.044
